name: Release Plugin Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dify plugin tool
        run: |
          curl -L -o dify-plugin-daemon.tar.gz https://github.com/langgenius/dify-plugin-daemon/releases/latest/download/dify-plugin-daemon-linux-amd64.tar.gz
          tar xzf dify-plugin-daemon.tar.gz
          sudo mv dify /usr/local/bin/

      - name: Package plugin
        run: |
          cd ..
          dify plugin package ./cosense-dify-plugin/cosense_search_tool
          cd cosense-dify-plugin

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Cosense Search Tool ${{ github.ref_name }}" \
            --notes "Automated release of Cosense Search Tool" \
            ../cosense_search_tool.difypkg
