name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'devin/*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dify plugin tool
        run: |
          curl -L -o dify https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.1/dify-plugin-linux-amd64
          chmod +x dify
          sudo mv dify /usr/local/bin/

      - name: Package plugin
        run: |
          cd ..
          dify plugin package ./cosense-dify-plugin/cosense_search_tool
          cd cosense-dify-plugin

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dify plugin tool
        run: |
          curl -L -o dify https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.1/dify-plugin-linux-amd64
          chmod +x dify
          sudo mv dify /usr/local/bin/

      - name: Package plugin
        run: |
          cd ..
          dify plugin package ./cosense-dify-plugin/cosense_search_tool
          cd cosense-dify-plugin

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: Build and run sign tool
        run: |
          git clone https://github.com/langgenius/dify-plugin-daemon.git
          cd dify-plugin-daemon
          # Generate RSA key pair
          openssl genrsa 4096 2>/dev/null | openssl rsa -traditional > internal/core/license/private_key/PRIVATE_KEY.pem
          chmod 600 internal/core/license/private_key/PRIVATE_KEY.pem
          # Build sign tool
          go build -o sign-tool ./cmd/license/sign
          # Sign plugin
          cd ..
          ./dify-plugin-daemon/sign-tool -in ../cosense_search_tool.difypkg -out ../cosense_search_tool_signed.difypkg

      - name: Generate version tag
        id: version
        run: |
          timestamp=$(date -u +%Y%m%d%H%M%S)
          echo "tag=v0.1.0-${timestamp}" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.version.outputs.tag }} \
            --title "Cosense Search Tool ${{ steps.version.outputs.tag }}" \
            --notes "Automated release from main branch" \
            ../cosense_search_tool_signed.difypkg
